# File paths
url:     "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
img:     "/_assets/img"
css:     "/_assets/css"
js:      "/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed

# Strapi settings
plugins:
  - jekyll-strapi

strapi:
    endpoint: http://localhost:1337
    collections:
        sites:
            type: sites
        posts:
            type: posts
            permalink: /posts/:slug/
            layout: post.html
            output: true
        projects:
            type: projects
            permalink: /projects/:slug/
            layout: project.html
            output: true