
# File paths
url:     "" # the base hostname & protocol for your site
baseurl: "/" # the subpath of your site, e.g. /blog/
img:     "/_assets/img"
css:     "/_assets/css"
js:      "/_assets/js"

# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed

# Global variables
title: Portfolio
description: Welcome to my little corner of the internet. I've been working in the field of design since 2009 with experience in everything from print and branding, to video editing and web development. My passion truly lies in developing brand systems that span all formats and create a joyful experience for people to discover.
